name: flutter_app_for_learn_widgets1
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  rxdart: ^0.27.5
  provider: ^6.0.4
  http: ^0.13.5
  json_serializable: ^6.5.3

  cupertino_icons: ^1.0.2
  flutter_bloc: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  build_runner: ^2.3.2


flutter:
  uses-material-design: true